name = "KFUPMCourseDB"
uuid = "239a9bc0-2518-4d67-ae60-5e41fb81336c"
authors = ["Mohammed Alshahrani <mmogib@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
